<a href="https://colab.research.google.com/github/Nissun662/Data-Visual/blob/main/Aayush_and_Nishan_Quiz_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Processing and Visualization
Nishan Sunar  
Aayush Bhurtel  
Quiz 6

Today's Assignment:  
Challenge your mates with a difficult question. Try to stump them and don't forget to try it yourself! For the quiz, pair (or thruple, three or less please!) up with someone in the class and try to come up with a challenge for you both to tackle. I'd prefer you consider the datasets we have already looked at; liquors, bikeshare (stations or trips) and census.

(Me and Aayush teamed up for this quiz and asked each other some challenging question. Here we have solved them.)

In [1]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

First, we need to get through the authorization process so that we can pull all the necessary dataset directly from Google Cloud Sandbox.

#Nishan's Turn
What is the difference in liquor sales in the POLK county of Iowa state in the month of April 2020 and 2021. This will give me a picture of decline/increase in liquor consumption as a result of stay at home order.

In [8]:
%%bigquery --project bustling-cosmos-338722
SELECT *
FROM `bigquery-public-data.iowa_liquor_sales.sales`
LIMIT 20

   invoice_and_item_number        date  ... volume_sold_liters volume_sold_gallons
0          INV-37596300067  2021-06-17  ...              660.0              174.35
1          INV-19930800010  2019-06-11  ...               48.0               12.68
2          INV-13427700191  2018-07-24  ...                4.0                1.06
3             S06959800006  2012-08-07  ...                5.0                1.32
4             S13503000052  2013-07-23  ...                4.0                1.06
5             S27471100001  2015-08-24  ...              240.0               63.40
6          INV-07193600144  2017-09-12  ...               72.0               19.02
7          INV-25545100048  2020-02-28  ...                2.0                0.52
8          INV-24900900101  2020-01-30  ...                6.0                1.58
9             S10669300010  2013-02-18  ...               60.0               15.85
10         INV-42339600005  2021-11-24  ...                0.2                0.05
11            S08928900025  2012-11-13  ...                4.0                1.06
12            S07572700028  2012-09-06  ...               63.0               16.64
13            S03777200033  2012-01-26  ...                0.4                0.11
14         INV-14188600030  2018-08-31  ...                2.0                0.52
15         INV-38258700028  2021-07-12  ...              660.0              174.35
16         INV-38334100022  2021-07-14  ...                0.2                0.05
17            S22615600004  2014-11-25  ...                4.8                1.27
18         INV-32523700041  2020-12-08  ...               72.0               19.02
19         INV-32594100011  2020-12-10  ...               90.0               23.77

[20 rows x 24 columns]

In [4]:
%%bigquery --project bustling-cosmos-338722 
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
LIMIT 100

       trip_id  ... duration_minutes
0   9900289692  ...               39
1   9900285987  ...               31
2   9900285989  ...               31
3   9900285991  ...               30
4   9900286140  ...               19
..         ...  ...              ...
95  9900290499  ...               11
96  9900290570  ...               23
97  9900290601  ...               18
98  9900290615  ...               17
99  9900290636  ...               25

[100 rows x 9 columns]