<a href="https://colab.research.google.com/github/Nissun662/Data-Visual/blob/main/Quiz17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Processing and Visualization
##Nishan Sunar
250662

#Today's Assignment: 
Grab the `iris` dataset.  Answer the following questions:

1. Does converting *SepalLength* to integer increase or decrease the mean?
2. Does the direction of the shift remain the same if you `groupby` Class?
3. Gather the mean, median, count and standard deviation of all columns when grouped by Class.

In [16]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')
df.head(10)

   SepalLength  SepalWidth  PedalLength  PedalWidth        Class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [17]:
df.SepalLength.dtypes

dtype('float64')

SepalLengh mean in `Float` datatype.

In [3]:
df.SepalLength.mean()

5.843333333333335

Converting the SepalLenght into `Integer` datatype and finding its mean.

In [4]:
df.SepalLength.astype('int').mean()

5.386666666666667

By looking at the above two output we can cleary say mean decreased after converting it into `int` dtypes.

Grouping the iris dataset by Class.

In [18]:
df.groupby('Class')
df.head(10)

   SepalLength  SepalWidth  PedalLength  PedalWidth        Class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

After I grouped the iris dataset by `Class` nothing changed so I would assume there is no change in the direction of shift.

## Finding the mean, median, count and standard deviation after grouping by Class.

In [19]:
df.groupby('Class').agg(['mean','median','count','std'])

                SepalLength               ... PedalWidth
                       mean median count  ...     median count       std
Class                                     ...
Iris-setosa           5.006    5.0    50  ...        0.2    50  0.107210
Iris-versicolor       5.936    5.9    50  ...        1.3    50  0.197753
Iris-virginica        6.588    6.5    50  ...        2.0    50  0.274650

[3 rows x 16 columns]